# Generated by Django 5.0.7 on 2024-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_delete_doctormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
